"""工人表调整\增加入职离职时间和当前状态

Revision ID: 0497376f31c1
Revises: 67a870c1b6da
Create Date: 2025-05-10 18:51:44.254541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0497376f31c1'
down_revision = '67a870c1b6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('leave_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('leave_date')
        batch_op.drop_column('entry_date')

    # ### end Alembic commands ###
