"""增加价格

Revision ID: 1048c6e39055
Revises: 20881617bec4
Create Date: 2025-11-25 17:25:57.641877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1048c6e39055'
down_revision = '20881617bec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wage_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_price', sa.Integer(), nullable=False, comment='实际工价'))
        batch_op.add_column(sa.Column('process_id', sa.Integer(), nullable=False, comment='关联的工序'))
        batch_op.create_foreign_key(None, 'processes', ['process_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wage_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('process_id')
        batch_op.drop_column('actual_price')

    # ### end Alembic commands ###
