"""增加规格价格字段

Revision ID: 20881617bec4
Revises: 824fba0ec677
Create Date: 2025-11-25 12:37:59.484614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20881617bec4'
down_revision = '824fba0ec677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spec_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='价格（元）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spec_models', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
