"""数据表枚举值修改

Revision ID: 568f4e8f5378
Revises: 4a52038cd988
Create Date: 2025-12-05 16:36:31.474536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '568f4e8f5378'
down_revision = '4a52038cd988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjustment_logs', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('rounding', 'write_off', 'manual', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('抹零', '勾账', '手动调整', name='adjustment_type'),
               existing_nullable=False)

    with op.batch_alter_table('company_accounts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'inactive', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('正常', '停用', name='company_account_status'),
               existing_nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('direction',
               existing_type=mysql.ENUM('income', 'expense', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('收入', '支出', name='transaction_direction'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'received', 'failed', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('待处理', '已到账', '失败', name='transaction_status'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('待处理', '已到账', '失败', name='transaction_status'),
               type_=mysql.ENUM('pending', 'received', 'failed', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('direction',
               existing_type=sa.Enum('收入', '支出', name='transaction_direction'),
               type_=mysql.ENUM('income', 'expense', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    with op.batch_alter_table('company_accounts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('正常', '停用', name='company_account_status'),
               type_=mysql.ENUM('active', 'inactive', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    with op.batch_alter_table('adjustment_logs', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('抹零', '勾账', '手动调整', name='adjustment_type'),
               type_=mysql.ENUM('rounding', 'write_off', 'manual', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    # ### end Alembic commands ###
