"""用户表和注册申请表对应

Revision ID: 6794e3e31ba3
Revises: ca46119d1769
Create Date: 2025-12-25 17:06:12.637132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6794e3e31ba3'
down_revision = 'ca46119d1769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('remark', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('remark')
        batch_op.drop_column('phone')
        batch_op.drop_column('real_name')

    # ### end Alembic commands ###
