"""工资记录表增加实际组人数字段

Revision ID: 67a870c1b6da
Revises: bc4aa4447575
Create Date: 2025-05-09 18:26:18.728397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a870c1b6da'
down_revision = 'bc4aa4447575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wage_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_group_size', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wage_logs', schema=None) as batch_op:
        batch_op.drop_column('actual_group_size')

    # ### end Alembic commands ###
