"""迁移数据库

Revision ID: 824fba0ec677
Revises: a07d4d595f7a
Create Date: 2025-11-22 21:56:28.618803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824fba0ec677'
down_revision = 'a07d4d595f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', sa.Text(), nullable=True, comment='备注'))
        batch_op.drop_index('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.drop_column('remark')

    # ### end Alembic commands ###
