"""库存相关表

Revision ID: 9554a83fad98
Revises: ef6a6c4d5d87
Create Date: 2026-01-02 12:00:19.710033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9554a83fad98'
down_revision = 'ef6a6c4d5d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='产品名称（规格生成后可人工调整）'),
    sa.Column('spec_json', sa.JSON(), nullable=False, comment='规格组合JSON（系统唯一识别依据）'),
    sa.Column('code', sa.String(length=100), nullable=True, comment='产品编码（对外 / ERP）'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否在用（停用不影响历史数据）'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('spec_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='规格编码，如 length / thickness'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='规格名称'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='产品ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='厂区 / 公司ID'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='厂区内部库存叫法（别名）'),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='当前库存数量'),
    sa.Column('warning_min_quantity', sa.Integer(), nullable=True, comment='库存预警下限'),
    sa.Column('warning_max_quantity', sa.Integer(), nullable=True, comment='库存预警上限'),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='参考成本价'),
    sa.Column('is_frozen', sa.Boolean(), nullable=True, comment='是否冻结（冻结后禁止出入库）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='盘点厂区 / 公司ID'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：pending / confirmed / canceled'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spec_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='规格分类ID'),
    sa.Column('value', sa.String(length=100), nullable=False, comment='规格值'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.ForeignKeyConstraint(['category_id'], ['spec_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_check_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False, comment='盘点单ID'),
    sa.Column('inventory_id', sa.Integer(), nullable=False, comment='库存ID'),
    sa.Column('system_quantity', sa.Integer(), nullable=False, comment='系统库存数量'),
    sa.Column('actual_quantity', sa.Integer(), nullable=False, comment='实际盘点数量'),
    sa.Column('difference', sa.Integer(), nullable=False, comment='盘点差异（实际 - 系统）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['check_id'], ['inventory_checks.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False, comment='库存ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='操作所属厂区 / 公司'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='操作用户ID'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型：in / out / adjust'),
    sa.Column('change_quantity', sa.Integer(), nullable=False, comment='变动数量（正负）'),
    sa.Column('before_quantity', sa.Integer(), nullable=False, comment='变动前库存'),
    sa.Column('after_quantity', sa.Integer(), nullable=False, comment='变动后库存'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_logs')
    op.drop_table('inventory_check_items')
    op.drop_table('spec_options')
    op.drop_table('inventory_checks')
    op.drop_table('inventories')
    op.drop_table('spec_categories')
    op.drop_table('products')
    # ### end Alembic commands ###
