"""更新数据库

Revision ID: a07d4d595f7a
Revises: a96f58383792
Create Date: 2025-11-22 19:11:43.363721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a07d4d595f7a'
down_revision = 'a96f58383792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wage_prices',
    sa.Column('id', sa.Integer(), nullable=False, comment='工价ID'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='工价（元/件）'),
    sa.Column('is_special', sa.Boolean(), nullable=True, comment='是否为特殊工价（如赶工、返工）'),
    sa.Column('effective_date', sa.Date(), nullable=True, comment='工价生效日期'),
    sa.Column('spec_model_id', sa.Integer(), nullable=False, comment='关联的规格型号ID'),
    sa.Column('process_id', sa.Integer(), nullable=False, comment='关联的工序ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.ForeignKeyConstraint(['spec_model_id'], ['spec_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='工序ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               comment="工序名称，如 '冲压'",
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               comment='工序描述',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)

    with op.batch_alter_table('spec_models', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='规格型号ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               comment="规格型号名称，如 'M20螺母'",
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               comment='产品分类',
               existing_nullable=True)
        batch_op.alter_column('process_id',
               existing_type=mysql.INTEGER(),
               comment='所属工序ID',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
        batch_op.drop_column('price')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, comment='角色：admin/user'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               comment='登录用户名',
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               comment='密码哈希值',
               existing_nullable=False)
        batch_op.alter_column('last_login_token',
               existing_type=mysql.VARCHAR(length=255),
               comment='上次登录的Token',
               existing_nullable=True)
        batch_op.alter_column('last_login_time',
               existing_type=mysql.DATETIME(),
               comment='上次登录时间',
               existing_nullable=True)

    with op.batch_alter_table('wage_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wage_price_id', sa.Integer(), nullable=True, comment='关联的工价ID'))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='工资记录ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               comment='记录日期',
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               comment='生产数量',
               existing_nullable=False)
        batch_op.alter_column('total_wage',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='总工资',
               existing_nullable=False)
        batch_op.alter_column('actual_group_size',
               existing_type=mysql.INTEGER(),
               comment='实际参与的班组人数',
               existing_nullable=False)
        batch_op.alter_column('remark',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               comment='备注信息',
               existing_nullable=True)
        batch_op.alter_column('worker_id',
               existing_type=mysql.INTEGER(),
               comment='关联的工人ID',
               existing_nullable=False)
        batch_op.alter_column('spec_model_id',
               existing_type=mysql.INTEGER(),
               comment='关联的规格型号ID',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
        batch_op.drop_constraint('wage_logs_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'wage_prices', ['wage_price_id'], ['id'])
        batch_op.drop_column('actual_price')
        batch_op.drop_column('is_special')
        batch_op.drop_column('process_id')

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='工人ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               comment='工人姓名',
               existing_nullable=False)
        batch_op.alter_column('id_card',
               existing_type=mysql.VARCHAR(length=18),
               comment='身份证号',
               existing_nullable=True)
        batch_op.alter_column('group',
               existing_type=mysql.VARCHAR(length=40),
               comment='班组，如 A组 / B组',
               existing_nullable=True)
        batch_op.alter_column('entry_date',
               existing_type=sa.DATE(),
               comment='入职日期',
               existing_nullable=True)
        batch_op.alter_column('leave_date',
               existing_type=sa.DATE(),
               comment='离职日期',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment='状态：在职 / 离职')
        batch_op.alter_column('process_id',
               existing_type=mysql.INTEGER(),
               comment='当前所属工序ID',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['id_card'])
        batch_op.drop_column('remark')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('process_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='当前所属工序ID',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment=None,
               existing_comment='状态：在职 / 离职')
        batch_op.alter_column('leave_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='离职日期',
               existing_nullable=True)
        batch_op.alter_column('entry_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='入职日期',
               existing_nullable=True)
        batch_op.alter_column('group',
               existing_type=mysql.VARCHAR(length=40),
               comment=None,
               existing_comment='班组，如 A组 / B组',
               existing_nullable=True)
        batch_op.alter_column('id_card',
               existing_type=mysql.VARCHAR(length=18),
               comment=None,
               existing_comment='身份证号',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='工人姓名',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='工人ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('wage_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_special', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('actual_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wage_logs_ibfk_1', 'processes', ['process_id'], ['id'])
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('spec_model_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联的规格型号ID',
               existing_nullable=False)
        batch_op.alter_column('worker_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联的工人ID',
               existing_nullable=False)
        batch_op.alter_column('remark',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='备注信息',
               existing_nullable=True)
        batch_op.alter_column('actual_group_size',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='实际参与的班组人数',
               existing_nullable=False)
        batch_op.alter_column('total_wage',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='总工资',
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='生产数量',
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='记录日期',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='工资记录ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('wage_price_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_login_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='上次登录时间',
               existing_nullable=True)
        batch_op.alter_column('last_login_token',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='上次登录的Token',
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='密码哈希值',
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='登录用户名',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')

    with op.batch_alter_table('spec_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('process_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属工序ID',
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='产品分类',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment="规格型号名称，如 'M20螺母'",
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='规格型号ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='工序描述',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment="工序名称，如 '冲压'",
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='工序ID',
               existing_nullable=False,
               autoincrement=True)

    op.drop_table('wage_prices')
    # ### end Alembic commands ###
