"""Add process_id to wage_prices

Revision ID: acabcf3f715d
Revises: cddae570e6e4
Create Date: 2025-04-24 19:32:23.890234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acabcf3f715d'
down_revision = 'cddae570e6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wage_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'processes', ['process_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wage_prices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('process_id')

    # ### end Alembic commands ###
