"""调整数据结构

Revision ID: c9d9de33d0d1
Revises: 1048c6e39055
Create Date: 2025-11-25 19:23:32.333466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9d9de33d0d1'
down_revision = '1048c6e39055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wage_prices')
    with op.batch_alter_table('wage_logs', schema=None) as batch_op:
        batch_op.alter_column('actual_price',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_comment='实际工价',
               existing_nullable=False)
        batch_op.drop_constraint('wage_logs_ibfk_4', type_='foreignkey')
        batch_op.drop_column('wage_price_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wage_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wage_price_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='关联的工价ID'))
        batch_op.create_foreign_key('wage_logs_ibfk_4', 'wage_prices', ['wage_price_id'], ['id'])
        batch_op.alter_column('actual_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_comment='实际工价',
               existing_nullable=False)

    op.create_table('wage_prices',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='工价ID'),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='工价（元/件）'),
    sa.Column('is_special', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否为特殊工价（如赶工、返工）'),
    sa.Column('effective_date', sa.DATE(), nullable=True, comment='工价生效日期'),
    sa.Column('spec_model_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='关联的规格型号ID'),
    sa.Column('process_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='关联的工序ID'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name='wage_prices_ibfk_1'),
    sa.ForeignKeyConstraint(['spec_model_id'], ['spec_models.id'], name='wage_prices_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
