"""注册表加入公司id字段

Revision ID: ef6a6c4d5d87
Revises: a1b2c3d4e5f6
Create Date: 2025-12-28 09:13:17.313672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6a6c4d5d87'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_registers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_registers_company_id'), ['company_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user_registers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_registers_company_id'))
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
